apiVersion: v1
kind: Service
metadata:
  name: iqtk-api
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: iqtk-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iqtk-api
  labels:
    app: iqtk
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: iqtk
        tier: api
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:8080",
          #"-a", "104.154.20.223", # Proxy to fission
          "-s", "SERVICE-NAME",
          "-v", "SERVICE-CONFIG-ID",
        ]
      # [END esp]
        ports:
        - containerPort: 8081
      - name: iqtk-api
        image: quay.io/iqtk/iqtk:0.0.4
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
          - name: PROCESSES
            value: api_service
