apiVersion: v1
kind: Pod
metadata:
  name: gcloud-auth-debug
spec:
  volumes:
  - name: google-cloud-key
    secret:
      secretName: gcloud-app-credentials-secret
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: google-cloud-key
      mountPath: /var/secrets/google
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
    - name: CLOUDSDK_CORE_PROJECT
      value: jbei-cloud
