apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iqtk-flow-runner
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: iqtk
        tier: worker
        service: flow-runner
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-app-credentials-secret
      containers:
      - name: iqtk-flow-runner
        image: quay.io/iqtk/iqtk:IQTK-DEPLOY-IMAGE-VERSION
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLOUDSDK_CORE_PROJECT
          value: IQTK-DEPLOY-PROJECT-ID
        - name: PROCESSES
          value: flow_runner
