# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bq_table_name.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bq_table_name.proto',
  package='gen_bq_schema',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x62q_table_name.proto\x12\rgen_bq_schema\x1a google/protobuf/descriptor.proto:4\n\ntable_name\x12\x1f.google.protobuf.MessageOptions\x18\xfd\x07 \x01(\tB\x06Z\x04main')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


TABLE_NAME_FIELD_NUMBER = 1021
table_name = _descriptor.FieldDescriptor(
  name='table_name', full_name='gen_bq_schema.table_name', index=0,
  number=1021, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['table_name'] = table_name

google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(table_name)

DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\004main'))
# @@protoc_insertion_point(module_scope)
