#!/bin/bash
# Copyright 2017 The Regents of the University of California
#
# Licensed under the BSD-3-clause license (the "License"); you may not
# use this file except in compliance with the License.
# You are provided a copy of the license in LICENSE.md at the root of
# this project.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

DATA_PATH=$1
REMOTE_TARGET=$2
GCP_SERVICE_ACCOUNT_KEY_PATH=$3
GCP_SERVICE_ACCOUNT=$4
IMAGE=gcr.io/jbei-data/uplink:0.0.1

# Yeah not the way to do this will ask mark....
KEY=`cat ${GCP_SERVICE_ACCOUNT_KEY_PATH}`

docker run -v ${DATA_PATH}:/mnt/data \
  -it --entrypoint /bin/bash $IMAGE \
  -c "echo '$KEY' > ~/key.json && uplink -l /mnt/data \
             -r ${REMOTE_TARGET} \
             -k ~/key.json \
             -s ${GCP_SERVICE_ACCOUNT}"
