apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iqtk-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: iqtk
        tier: iqtk-service
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-app-credentials-secret
      containers:
      - name: iqtk-service
        image: quay.io/iqtk/iqtk:0.0.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: CLOUDSDK_CORE_PROJECT
          value: jbei-cloud
