# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agilent_mass_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agilent_mass_spec.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x61gilent_mass_spec.proto\"\x1a\n\x18\x41gilentMassSpecRunConfig')
)




_AGILENTMASSSPECRUNCONFIG = _descriptor.Descriptor(
  name='AgilentMassSpecRunConfig',
  full_name='AgilentMassSpecRunConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['AgilentMassSpecRunConfig'] = _AGILENTMASSSPECRUNCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgilentMassSpecRunConfig = _reflection.GeneratedProtocolMessageType('AgilentMassSpecRunConfig', (_message.Message,), dict(
  DESCRIPTOR = _AGILENTMASSSPECRUNCONFIG,
  __module__ = 'agilent_mass_spec_pb2'
  # @@protoc_insertion_point(class_scope:AgilentMassSpecRunConfig)
  ))
_sym_db.RegisterMessage(AgilentMassSpecRunConfig)


# @@protoc_insertion_point(module_scope)
