# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='device_config.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x64\x65vice_config.proto\"\x1c\n\x0c\x44\x65viceConfig\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')
)




_DEVICECONFIG = _descriptor.Descriptor(
  name='DeviceConfig',
  full_name='DeviceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DeviceConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['DeviceConfig'] = _DEVICECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceConfig = _reflection.GeneratedProtocolMessageType('DeviceConfig', (_message.Message,), dict(
  DESCRIPTOR = _DEVICECONFIG,
  __module__ = 'device_config_pb2'
  # @@protoc_insertion_point(class_scope:DeviceConfig)
  ))
_sym_db.RegisterMessage(DeviceConfig)


# @@protoc_insertion_point(module_scope)
