# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miseq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='miseq.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bmiseq.proto\"\x9c\x01\n\x0bMiSeqSample\x12\x11\n\tsample_id\x18\x01 \x02(\t\x12\x14\n\x0csample_plate\x18\x02 \x02(\t\x12\x13\n\x0bsample_well\x18\x03 \x02(\t\x12\x13\n\x0bi7_index_id\x18\x04 \x02(\t\x12\r\n\x05index\x18\x05 \x02(\t\x12\x16\n\x0esample_project\x18\x06 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x02(\t\"\xc7\x02\n\x0eMiSeqRunConfig\x12\x18\n\x10iem_file_version\x18\x01 \x02(\x05\x12\x19\n\x11investigator_name\x18\x02 \x02(\t\x12\x17\n\x0f\x65xperiment_name\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x02(\t\x12\x10\n\x08workflow\x18\x05 \x02(\t\x12\x13\n\x0b\x61pplication\x18\x06 \x02(\t\x12\r\n\x05\x61ssay\x18\x07 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x02(\t\x12\x11\n\tchemistry\x18\t \x02(\t\x12\x16\n\x0eread_1_adapter\x18\n \x02(\t\x12\x16\n\x0eread_2_adapter\x18\x0b \x02(\t\x12\x15\n\rread_1_length\x18\x0c \x02(\x05\x12\x15\n\rread_2_length\x18\r \x02(\x05\x12\x1d\n\x07samples\x18\x0e \x03(\x0b\x32\x0c.MiSeqSample\"4\n\x0bSampleFastq\x12\x11\n\tsample_id\x18\x01 \x02(\t\x12\x12\n\nfastq_path\x18\x02 \x02(\t\"O\n\x08MiSeqRun\x12\x1f\n\x06\x63onfig\x18\x01 \x02(\x0b\x32\x0f.MiSeqRunConfig\x12\"\n\x0csample_fastq\x18\x02 \x03(\x0b\x32\x0c.SampleFastq')
)




_MISEQSAMPLE = _descriptor.Descriptor(
  name='MiSeqSample',
  full_name='MiSeqSample',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_id', full_name='MiSeqSample.sample_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_plate', full_name='MiSeqSample.sample_plate', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_well', full_name='MiSeqSample.sample_well', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i7_index_id', full_name='MiSeqSample.i7_index_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='MiSeqSample.index', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_project', full_name='MiSeqSample.sample_project', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='MiSeqSample.description', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=172,
)


_MISEQRUNCONFIG = _descriptor.Descriptor(
  name='MiSeqRunConfig',
  full_name='MiSeqRunConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iem_file_version', full_name='MiSeqRunConfig.iem_file_version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='investigator_name', full_name='MiSeqRunConfig.investigator_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experiment_name', full_name='MiSeqRunConfig.experiment_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='MiSeqRunConfig.date', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workflow', full_name='MiSeqRunConfig.workflow', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='application', full_name='MiSeqRunConfig.application', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='assay', full_name='MiSeqRunConfig.assay', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='MiSeqRunConfig.description', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chemistry', full_name='MiSeqRunConfig.chemistry', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_1_adapter', full_name='MiSeqRunConfig.read_1_adapter', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_2_adapter', full_name='MiSeqRunConfig.read_2_adapter', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_1_length', full_name='MiSeqRunConfig.read_1_length', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='read_2_length', full_name='MiSeqRunConfig.read_2_length', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='samples', full_name='MiSeqRunConfig.samples', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=502,
)


_SAMPLEFASTQ = _descriptor.Descriptor(
  name='SampleFastq',
  full_name='SampleFastq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sample_id', full_name='SampleFastq.sample_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fastq_path', full_name='SampleFastq.fastq_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=556,
)


_MISEQRUN = _descriptor.Descriptor(
  name='MiSeqRun',
  full_name='MiSeqRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='MiSeqRun.config', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_fastq', full_name='MiSeqRun.sample_fastq', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=558,
  serialized_end=637,
)

_MISEQRUNCONFIG.fields_by_name['samples'].message_type = _MISEQSAMPLE
_MISEQRUN.fields_by_name['config'].message_type = _MISEQRUNCONFIG
_MISEQRUN.fields_by_name['sample_fastq'].message_type = _SAMPLEFASTQ
DESCRIPTOR.message_types_by_name['MiSeqSample'] = _MISEQSAMPLE
DESCRIPTOR.message_types_by_name['MiSeqRunConfig'] = _MISEQRUNCONFIG
DESCRIPTOR.message_types_by_name['SampleFastq'] = _SAMPLEFASTQ
DESCRIPTOR.message_types_by_name['MiSeqRun'] = _MISEQRUN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MiSeqSample = _reflection.GeneratedProtocolMessageType('MiSeqSample', (_message.Message,), dict(
  DESCRIPTOR = _MISEQSAMPLE,
  __module__ = 'miseq_pb2'
  # @@protoc_insertion_point(class_scope:MiSeqSample)
  ))
_sym_db.RegisterMessage(MiSeqSample)

MiSeqRunConfig = _reflection.GeneratedProtocolMessageType('MiSeqRunConfig', (_message.Message,), dict(
  DESCRIPTOR = _MISEQRUNCONFIG,
  __module__ = 'miseq_pb2'
  # @@protoc_insertion_point(class_scope:MiSeqRunConfig)
  ))
_sym_db.RegisterMessage(MiSeqRunConfig)

SampleFastq = _reflection.GeneratedProtocolMessageType('SampleFastq', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLEFASTQ,
  __module__ = 'miseq_pb2'
  # @@protoc_insertion_point(class_scope:SampleFastq)
  ))
_sym_db.RegisterMessage(SampleFastq)

MiSeqRun = _reflection.GeneratedProtocolMessageType('MiSeqRun', (_message.Message,), dict(
  DESCRIPTOR = _MISEQRUN,
  __module__ = 'miseq_pb2'
  # @@protoc_insertion_point(class_scope:MiSeqRun)
  ))
_sym_db.RegisterMessage(MiSeqRun)


# @@protoc_insertion_point(module_scope)
