# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inquiry/toolkit/expression/schemas/expression_table.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bq_table_name_pb2 as bq__table__name__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inquiry/toolkit/expression/schemas/expression_table.proto',
  package='inquiry.toolkit.expression.schemas',
  syntax='proto3',
  serialized_pb=_b('\n9inquiry/toolkit/expression/schemas/expression_table.proto\x12\"inquiry.toolkit.expression.schemas\x1a\x13\x62q_table_name.proto\"\xa8\x02\n\x13\x44iffExpressionLevel\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06geneid\x18\x02 \x01(\t\x12\x0c\n\x04gene\x18\x03 \x01(\t\x12\r\n\x05locus\x18\x04 \x01(\t\x12\x0f\n\x07sample1\x18\x05 \x01(\t\x12\x0f\n\x07sample2\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x13\n\x0b\x65xpression1\x18\x08 \x01(\x02\x12\x13\n\x0b\x65xpression2\x18\t \x01(\x02\x12\x14\n\x0clnFoldChange\x18\n \x01(\x02\x12\x15\n\rtestStatistic\x18\x0b \x01(\x02\x12\x0e\n\x06pValue\x18\x0c \x01(\x02\x12\x0e\n\x06qValue\x18\r \x01(\x02\x12\x13\n\x0bsignificant\x18\x0e \x01(\x08:\x1a\xea?\x17\x64ifferential_expressionb\x06proto3')
  ,
  dependencies=[bq__table__name__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DIFFEXPRESSIONLEVEL = _descriptor.Descriptor(
  name='DiffExpressionLevel',
  full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geneid', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.geneid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gene', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.gene', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='locus', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.locus', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample1', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.sample1', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample2', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.sample2', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.status', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expression1', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.expression1', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expression2', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.expression2', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lnFoldChange', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.lnFoldChange', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='testStatistic', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.testStatistic', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pValue', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.pValue', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qValue', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.qValue', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='significant', full_name='inquiry.toolkit.expression.schemas.DiffExpressionLevel.significant', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\352?\027differential_expression')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=415,
)

DESCRIPTOR.message_types_by_name['DiffExpressionLevel'] = _DIFFEXPRESSIONLEVEL

DiffExpressionLevel = _reflection.GeneratedProtocolMessageType('DiffExpressionLevel', (_message.Message,), dict(
  DESCRIPTOR = _DIFFEXPRESSIONLEVEL,
  __module__ = 'inquiry.toolkit.expression.schemas.expression_table_pb2'
  # @@protoc_insertion_point(class_scope:inquiry.toolkit.expression.schemas.DiffExpressionLevel)
  ))
_sym_db.RegisterMessage(DiffExpressionLevel)


_DIFFEXPRESSIONLEVEL.has_options = True
_DIFFEXPRESSIONLEVEL._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\352?\027differential_expression'))
# @@protoc_insertion_point(module_scope)
