# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mass_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mass_spec.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmass_spec.proto\x1a\x0c\x63ommon.proto\"\xa5\x02\n\x10MSQuantification\x12\x13\n\x0b\x63ompound_id\x18\x01 \x01(\t\x12\x0f\n\x07Pathway\x18\x02 \x01(\t\x12\x13\n\x0bsub_pathway\x18\x03 \x01(\t\x12\x0f\n\x07kegg_id\x18\x04 \x01(\t\x12\x12\n\npubchem_id\x18\x05 \x01(\x05\x12\x10\n\x08platform\x18\x06 \x01(\t\x12\x0c\n\x04hmdb\x18\x07 \x01(\t\x12\x18\n\x10\x62iochemical_name\x18\x08 \x01(\t\x12\x0c\n\x04mass\x18\t \x01(\x02\x12\x17\n\x0fretention_index\x18\n \x01(\x02\x12\x12\n\ncas_number\x18\x0b \x01(\t\x12\x1b\n\x13\x63onfidence_interval\x18\x0c \x01(\x02\x12\x1f\n\nattributes\x18\r \x01(\x0b\x32\x0b.Attributesb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_MSQUANTIFICATION = _descriptor.Descriptor(
  name='MSQuantification',
  full_name='MSQuantification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compound_id', full_name='MSQuantification.compound_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Pathway', full_name='MSQuantification.Pathway', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub_pathway', full_name='MSQuantification.sub_pathway', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kegg_id', full_name='MSQuantification.kegg_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pubchem_id', full_name='MSQuantification.pubchem_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='platform', full_name='MSQuantification.platform', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hmdb', full_name='MSQuantification.hmdb', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biochemical_name', full_name='MSQuantification.biochemical_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mass', full_name='MSQuantification.mass', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retention_index', full_name='MSQuantification.retention_index', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cas_number', full_name='MSQuantification.cas_number', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confidence_interval', full_name='MSQuantification.confidence_interval', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='MSQuantification.attributes', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=327,
)

_MSQUANTIFICATION.fields_by_name['attributes'].message_type = common__pb2._ATTRIBUTES
DESCRIPTOR.message_types_by_name['MSQuantification'] = _MSQUANTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MSQuantification = _reflection.GeneratedProtocolMessageType('MSQuantification', (_message.Message,), dict(
  DESCRIPTOR = _MSQUANTIFICATION,
  __module__ = 'mass_spec_pb2'
  # @@protoc_insertion_point(class_scope:MSQuantification)
  ))
_sym_db.RegisterMessage(MSQuantification)


# @@protoc_insertion_point(module_scope)
